#!/bin/bash

if [ $3 -eq 0 ]
	then 
	echo "Invalid input. 0 cannot be taken"
else
case $2 in
'+') sum=$(($1 + $3))
echo $sum
;;
'-') sub=$(($1 - $3))
echo $sub
;;
'x') mult=$(($1 * $3))
echo $mult
;;
'/') div=$(($1 / $3))
echo $div
;;
esac
fi
