#!/bin/bash

declare -a arr

 neg=0
 posi=0
 z=0
 t=0
echo Enter ten nos

for(( i=0; i<10; i++ ))
do
   read arr[i]
done


for(( i=0; i<10; i++ ))
 do
    if [ ${arr[$i]} -lt 0 ]
    then
       neg=$((neg+1))
    elif [ ${arr[$i]} -gt 0 ]
    then
       posi=$((posi+1))
    else
       z=$((z+1))
    fi
 done

echo "${arr[*]}"

echo "Negative: $neg Positive: $posi Zero: $z"

for (( i = 0; i < 9 ; i++ ))
do
for (( j = 0; j < 9; j++ ))
do
if [[ "${arr[$j]}" > "${arr[$j+1]}" ]]; then
t=${arr[$j]}
arr[$j]=${arr[$j+1]}
arr[$j+1]=$t
fi
done
done

echo "${arr[*]}"
