#!/bin/bash

declare -a array

pos=0
neg=0
zer=0

for((i=0; i<10; i++))
do
	read array[i]
done

for((i=0; i<10; i++))
do
	if [ ${array[$i]} -lt 0 ]
		then
		neg=$((neg+1))
	elif [ ${array[$i]} -gt 0 ]
		then
		pos=$((pos+1))
	else
		zer=$((zer+1))
	fi
done

echo "Positive numbers:$pos"
echo "Negative Numbers:$neg"
echo "Zero:$zer"

