#!/bin/bash
echo -n "Enter file or dir name : "
read name

if [ -d $name ]
then
    echo "Given name is directory"
    echo `ls $name`
elif [ -f $name ]
then
    echo "File name is : $name"
    cat $name
    echo "No of line in file is : `wc -l $name | cut -d "" -f1`"
fi
